spring:
  application:
    name: jan-2024-java-spring
  datasource:
    url: "jdbc:mysql://localhost:3306/march-2024-java?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update